#!/bin/sh

# xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --auto
[ -f /usr/bin/prime-offload ] && /usr/bin/prime-offload

# Source xprofile
[ -f "${XDG_CONFIG_HOME}/X11/xprofile" ] && . "${XDG_CONFIG_HOME}/X11/xprofile"

# xsetroot -solid "#edbcb9"
export STATUSBAR="i3blocks"
exec i3

