#!/bin/sh

##################################################
#                                                #
# This file is deprecated. ly-dm loads .xprofile #
#                                                #
##################################################

# Run opimus-prime script if we have it
[ -f /usr/bin/prime-offload ] && /usr/bin/prime-offload

# Variables
export STATUSBAR="i3blocks"
export XDG_CONFIG_HOME="$HOME/.config"
export MICROPHONE="alsa_input.usb-Schiit_Audio_I_m_Fulla_Schiit-00.iec958-stereo"
export HEADPHONES="alsa_output.usb-Schiit_Audio_I_m_Fulla_Schiit-00.iec958-stereo"
export SPEAKERS="alsa_output.pci-0000_03_00.1.hdmi-stereo-extra2"

# Fix Gnome Apps Slow Start due to failing services
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# start some nice programs (from default xinitrc)
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Setup desktop
pipewire-pulse start
sxhkd &
xrdb $XDG_CONFIG_HOME/X11/Xresources
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

exec i3

