#!/bin/sh

# Variables
export STATUSBAR="i3blocks"
export XDG_CONFIG_HOME="$HOME/.config"

# Fix Gnome Apps Slow Start due to failing services
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# start some nice programs (from default xinitrc)
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Setup commands
# setxkbmap -option caps:swapescape
sxhkd &
# wal -i ~/.config/wallpapers/winter.jpeg
xrdb $XDG_CONFIG_HOME/X11/Xresources
# xrdb -merge $XDG_CACHE_HOME/wal/colors.Xresources
# redshift -P -O 3200
# find out if we want to use this instead
# unclutter &
