use_dark_theme = true

[[sources]]
name = 'alsa_input.usb-Schiit_Audio_I_m_Fulla_Schiit-00.iec958-stereo'
label = 'Mic'
hidden = false

[[sources]]
name = 'alsa_output.pci-0000_03_00.1.hdmi-stereo-extra2.monitor'
label = 'Monitor of Navi 21/23 HDMI/DP Audio Controller Digital Stereo (HDMI 3)'
hidden = true

[[sources]]
name = 'alsa_output.usb-Schiit_Audio_I_m_Fulla_Schiit-00.iec958-stereo.monitor'
label = '''Monitor of I'm Fulla Schiit Digital Stereo (IEC958)'''
hidden = true

[[sources]]
name = 'alsa_output.usb-Schiit_Audio_I_m_Fulla_Schiit-00.iec958-stereo.echo-cancel.monitor'
label = '''Monitor of I'm Fulla Schiit Digital Stereo (IEC958) (echo cancelled with I'm Fulla Schiit Digital Stereo (IEC958))'''
hidden = true

[[sources]]
name = 'echo_cancel_sink.monitor'
label = '''Monitor of I'm Fulla Schiit Digital Stereo (IEC958) (echo cancelled with I'm Fulla Schiit Digital Stereo (IEC958))'''
hidden = true

[[sources]]
name = 'alsa_input.usb-046d_C922_Pro_Stream_Webcam_9360D0BF-02.iec958-stereo'
label = 'Webcam'
hidden = false

[[sources]]
name = 'alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source'
label = 'Mic'
hidden = false

[[sources]]
name = 'alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic2__source'
label = 'Tiger Lake-LP Smart Sound Technology Audio Controller Stereo Microphone'
hidden = true

[[sources]]
name = 'alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__HDMI1__sink.monitor'
label = 'Monitor of Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 1 Output'
hidden = true

[[sources]]
name = 'alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__HDMI2__sink.monitor'
label = 'Monitor of Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 2 Output'
hidden = true

[[sources]]
name = 'alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__HDMI3__sink.monitor'
label = 'Monitor of Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 3 Output'
hidden = true

[[sources]]
name = 'alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink.monitor'
label = 'Monitor of Tiger Lake-LP Smart Sound Technology Audio Controller Speaker'
hidden = true

[[sinks]]
name = 'alsa_output.usb-Schiit_Audio_I_m_Fulla_Schiit-00.iec958-stereo'
label = 'Headphones'
hidden = false

[[sinks]]
name = 'alsa_output.pci-0000_03_00.1.hdmi-stereo-extra2'
label = 'Speakers'
hidden = false

[[sinks]]
name = 'alsa_output.usb-Schiit_Audio_I_m_Fulla_Schiit-00.iec958-stereo.echo-cancel'
label = '''I'm Fulla Schiit Digital Stereo (IEC958) (echo cancelled with I'm Fulla Schiit Digital Stereo (IEC958))'''
hidden = true

[[sinks]]
name = 'echo_cancel_sink'
label = '''I'm Fulla Schiit Digital Stereo (IEC958) (echo cancelled with I'm Fulla Schiit Digital Stereo (IEC958))'''
hidden = true

[[sinks]]
name = 'alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__HDMI1__sink'
label = 'Display 1'
hidden = false

[[sinks]]
name = 'alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__HDMI2__sink'
label = 'Display 2'
hidden = false

[[sinks]]
name = 'alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__HDMI3__sink'
label = 'Display 3'
hidden = false

[[sinks]]
name = 'alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink'
label = 'Speaker'
hidden = false
